#!/usr/bin/env python3
"""
manage_gallery.py

Add or replace a piece in the gallery/ folder, and regenerate the
auto-generated gallery grid in the repo's README.md to match.

RUN FROM INSIDE gallery/:

    cd gallery
    python3 ../scripts/manage_gallery.py /path/to/finished_photo.jpg

WHAT IT DOES, IN ORDER
-----------------------
1. Requires a file named exactly `_index.png` to already be sitting in the
   CURRENT directory (i.e. gallery/) -- this is the index sheet
   ti_mosaic_separator.py writes for a run. Copy/move that run's
   _index.png here before calling this script. Errors out if it's missing,
   so you never accidentally pair a piece with the wrong index sheet.
2. Takes the image argument and converts it to .jpg if it isn't already
   one (handles HEIC/PNG/anything Pillow reads; fixes EXIF rotation).
   No cropping or perspective correction is done here -- bring your own
   already-finished image (e.g. from extract_and_dekeystone.py + your own
   tighter manual crop).
3. Creates gallery/<piece-name>/ from the image's filename (no extension).
   If that folder already exists, this is a REPLACE: old image files in
   it are removed first, so a changed extension doesn't leave stale
   files behind.
4. Moves the converted jpg and _index.png into that folder as
   <piece-name>.jpg and _index.png.
5. Rewrites the block between the `GALLERY:START` / `GALLERY:END` markers
   in ../README.md (configurable with --readme) with an image+caption grid
   of every piece currently in gallery/, sorted by folder name. Everything
   else in the README is left untouched. If the markers aren't found, a
   new "## Gallery" section is appended at the end -- move it wherever you
   like afterwards, the markers travel with it.

Per-piece caption: put an optional gallery/<piece-name>/caption.txt with a
short line of text (e.g. "9-color, dinosaur against open sky") and it'll
be used instead of the auto-titled folder name.

Safe to re-run. Re-adding the same piece replaces its contents; adding a
new piece just adds another entry to the grid.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageOps

HEIC_EXTS = {".heic", ".heif"}
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".heic", ".heif", ".tif", ".tiff", ".bmp", ".webp"}

GALLERY_START = "<!-- GALLERY:START (auto-generated by scripts/manage_gallery.py -- do not hand-edit this block) -->"
GALLERY_END = "<!-- GALLERY:END -->"


# --------------------------------------------------------------------------
# Image loading / conversion
# --------------------------------------------------------------------------

def _load_heic_via_pillow_heif(path: Path) -> Image.Image:
    import pillow_heif  # raises ImportError if not installed
    heif_file = pillow_heif.open_heif(str(path), convert_hdr_to_8bit=True)
    return heif_file.to_pillow()


def _load_heic_via_sips(path: Path) -> Image.Image:
    # macOS-only fallback: sips ships with every Mac, no extra install needed.
    with tempfile.TemporaryDirectory() as tmp:
        out_path = Path(tmp) / "converted.png"
        result = subprocess.run(
            ["sips", "-s", "format", "png", str(path), "--out", str(out_path)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"sips conversion failed: {result.stderr.strip()}")
        return Image.open(out_path).convert("RGB")


def load_as_pil(path: Path) -> Image.Image:
    if path.suffix.lower() in HEIC_EXTS:
        try:
            img = _load_heic_via_pillow_heif(path)
        except ImportError:
            try:
                img = _load_heic_via_sips(path)
            except (FileNotFoundError, RuntimeError) as e:
                raise SystemExit(
                    f"Can't read HEIC/HEIF file: {path}\n"
                    f"Install support with:  pip install pillow-heif\n"
                    f"(macOS-only 'sips' fallback also failed: {e})"
                )
    else:
        img = Image.open(path)
    img = ImageOps.exif_transpose(img)  # apply EXIF rotation if present
    return img.convert("RGB")


def convert_to_jpg(src: Path, dst: Path, quality: int = 95) -> None:
    if src.resolve() == dst.resolve():
        return
    if src.suffix.lower() in {".jpg", ".jpeg"}:
        shutil.copy2(src, dst)
        return
    img = load_as_pil(src)
    img.save(dst, "JPEG", quality=quality)


# --------------------------------------------------------------------------
# README gallery block generation
# --------------------------------------------------------------------------

def stem_to_title(stem: str) -> str:
    return stem.replace("_", " ").replace("-", " ").strip().title()


def collect_pieces(gallery_dir: Path, skip_dirs=("hero", "failures")):
    pieces = []
    for d in sorted(gallery_dir.iterdir()):
        if not d.is_dir() or d.name in skip_dirs:
            continue
        images = sorted(d.glob("*.jpg")) + sorted(d.glob("*.jpeg"))
        if not images:
            continue
        image = images[0]
        index_sheet = d / "_index.png"
        caption_file = d / "caption.txt"
        if caption_file.exists():
            first_line = caption_file.read_text().strip().splitlines()
            caption = first_line[0] if first_line else stem_to_title(d.name)
        else:
            caption = stem_to_title(d.name)
        pieces.append({
            "name": d.name,
            "image": image,
            "index_sheet": index_sheet if index_sheet.exists() else None,
            "caption": caption,
        })
    return pieces


def build_gallery_block(pieces, readme_root: Path) -> str:
    lines = [GALLERY_START, ""]

    if not pieces:
        lines.append("_Gallery is empty -- add a piece with `scripts/manage_gallery.py`._")
        lines.append("")
        lines.append(GALLERY_END)
        return "\n".join(lines)

    def rel(p: Path) -> str:
        try:
            return p.resolve().relative_to(readme_root.resolve()).as_posix()
        except ValueError:
            return p.as_posix()

    lines.append("<table>")
    lines.append("  <tr>")
    for i, piece in enumerate(pieces):
        cell = [
            '    <td width="33%" align="center">',
            f'      <img src="{rel(piece["image"])}" alt="{piece["caption"]}" width="100%"><br>',
            f'      <sub><b>{piece["caption"]}</b></sub>',
        ]
        if piece["index_sheet"] is not None:
            cell.append(f'      <br><sub><a href="{rel(piece["index_sheet"])}">index sheet</a></sub>')
        cell.append("    </td>")
        lines.extend(cell)
        is_last = i == len(pieces) - 1
        if (i + 1) % 3 == 0 and not is_last:
            lines.append("  </tr>")
            lines.append("  <tr>")
    lines.append("  </tr>")
    lines.append("</table>")
    lines.append("")
    lines.append(GALLERY_END)
    return "\n".join(lines)


def regenerate_readme(gallery_dir: Path, readme_path: Path) -> None:
    if not readme_path.exists():
        raise SystemExit(
            f"README not found at {readme_path}.\n"
            f"Pass --readme to point at it, or create it first."
        )

    pieces = collect_pieces(gallery_dir)
    block = build_gallery_block(pieces, readme_root=readme_path.resolve().parent)

    text = readme_path.read_text()
    if GALLERY_START in text and GALLERY_END in text:
        pre = text.split(GALLERY_START)[0]
        post = text.split(GALLERY_END)[1]
        new_text = pre + block + post
        note = "Updated existing gallery block"
    else:
        new_text = text.rstrip("\n") + "\n\n## Gallery\n\n" + block + "\n"
        note = "No gallery markers found -- appended a new '## Gallery' section"

    readme_path.write_text(new_text)
    print(f"{note} in {readme_path} ({len(pieces)} piece(s)).")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image", type=Path, help="finished photo to add/replace in the gallery")
    ap.add_argument("--quality", type=int, default=95, help="JPEG quality if conversion is needed (default 95)")
    ap.add_argument("--readme", type=Path, default=Path("../README.md"),
                     help="path to the README.md to update (default: ../README.md)")
    args = ap.parse_args()

    gallery_dir = Path(".").resolve()

    index_src = gallery_dir / "_index.png"
    if not index_src.exists():
        raise SystemExit(
            f"Expected an _index.png in {gallery_dir} (the separator's index sheet "
            f"for this piece) but didn't find one.\n"
            f"Drop the run's _index.png here before running this script."
        )

    if not args.image.exists():
        raise SystemExit(f"Image not found: {args.image}")
    if args.image.suffix.lower() not in IMAGE_EXTS:
        raise SystemExit(f"Unrecognized image type: {args.image.suffix}")

    piece_name = args.image.stem
    piece_dir = gallery_dir / piece_name
    is_replace = piece_dir.exists()
    piece_dir.mkdir(exist_ok=True)

    # Clear stale image files from a previous version of this piece (e.g.
    # extension changed between runs) -- but never touch caption.txt.
    for old in piece_dir.iterdir():
        if old.suffix.lower() in IMAGE_EXTS:
            old.unlink()

    dst_image = piece_dir / f"{piece_name}.jpg"
    convert_to_jpg(args.image, dst_image, quality=args.quality)

    dst_index = piece_dir / "_index.png"
    shutil.move(str(index_src), str(dst_index))

    print(f"{'Replaced' if is_replace else 'Added'} '{piece_name}' -> {piece_dir}/")

    regenerate_readme(gallery_dir, args.readme)


if __name__ == "__main__":
    main()
