#!/usr/bin/env python3
"""
manage_gallery.py

Add or replace a piece in the gallery/ folder, and regenerate gallery/README.md
so it shows every piece with its finished photo directly beside the full-sized
index sheet -- the point being to make the layer-by-layer labor visible, not
buried behind a link.

RUN FROM INSIDE gallery/:

    cd gallery
    python3 ../scripts/manage_gallery.py /path/to/finished_photo.jpg

WHAT IT DOES, IN ORDER
-----------------------
1. Requires a file named exactly `_index.png` to already be sitting in the
   CURRENT directory (i.e. gallery/) -- this is the index sheet
   ti_mosaic_separator.py writes for a run. Copy/move that run's
   _index.png here before calling this script. Errors out if it's missing,
   so you never accidentally pair a piece with the wrong index sheet.
2. Takes the image argument and converts it to .jpg if it isn't already
   one (handles HEIC/PNG/anything Pillow reads; fixes EXIF rotation).
   No cropping or perspective correction is done here -- bring your own
   already-finished image (e.g. from extract_and_dekeystone.py + your own
   tighter manual crop).
3. Creates gallery/<piece-name>/ from the image's filename (no extension).
   If that folder already exists, this is a REPLACE: old image files in
   it are removed first, so a changed extension doesn't leave stale
   files behind.
4. Moves the converted jpg and _index.png into that folder as
   <piece-name>.jpg and _index.png.
5. Rewrites the block between the `GALLERY:START` / `GALLERY:END` markers in
   gallery/README.md (configurable with --readme) with one section per piece:
   a heading, an optional caption, and the finished photo side by side with
   the full index sheet -- both sized to fill their half of the row, not
   shrunk to a thumbnail. Anything outside the markers (e.g. a hand-written
   intro) is left untouched. If gallery/README.md doesn't exist yet, or
   exists without markers, a sensible default is created/appended.

Per-piece caption: put an optional gallery/<piece-name>/caption.txt with a
short line of text (e.g. "9-color, dinosaur against open sky") and it'll be
shown under that piece's heading.

Safe to re-run. Re-adding the same piece replaces its contents; adding a
new piece just adds another section.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageOps

HEIC_EXTS = {".heic", ".heif"}
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".heic", ".heif", ".tif", ".tiff", ".bmp", ".webp"}

GALLERY_START = "<!-- GALLERY:START (auto-generated by scripts/manage_gallery.py -- do not hand-edit this block) -->"
GALLERY_END = "<!-- GALLERY:END -->"


# --------------------------------------------------------------------------
# Image loading / conversion
# --------------------------------------------------------------------------

def _load_heic_via_pillow_heif(path: Path) -> Image.Image:
    import pillow_heif  # raises ImportError if not installed
    heif_file = pillow_heif.open_heif(str(path), convert_hdr_to_8bit=True)
    return heif_file.to_pillow()


def _load_heic_via_sips(path: Path) -> Image.Image:
    # macOS-only fallback: sips ships with every Mac, no extra install needed.
    with tempfile.TemporaryDirectory() as tmp:
        out_path = Path(tmp) / "converted.png"
        result = subprocess.run(
            ["sips", "-s", "format", "png", str(path), "--out", str(out_path)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"sips conversion failed: {result.stderr.strip()}")
        return Image.open(out_path).convert("RGB")


def load_as_pil(path: Path) -> Image.Image:
    if path.suffix.lower() in HEIC_EXTS:
        try:
            img = _load_heic_via_pillow_heif(path)
        except ImportError:
            try:
                img = _load_heic_via_sips(path)
            except (FileNotFoundError, RuntimeError) as e:
                raise SystemExit(
                    f"Can't read HEIC/HEIF file: {path}\n"
                    f"Install support with:  pip install pillow-heif\n"
                    f"(macOS-only 'sips' fallback also failed: {e})"
                )
    else:
        img = Image.open(path)
    img = ImageOps.exif_transpose(img)  # apply EXIF rotation if present
    return img.convert("RGB")


def convert_to_jpg(src: Path, dst: Path, quality: int = 95) -> None:
    if src.resolve() == dst.resolve():
        return
    if src.suffix.lower() in {".jpg", ".jpeg"}:
        shutil.copy2(src, dst)
        return
    img = load_as_pil(src)
    img.save(dst, "JPEG", quality=quality)


# --------------------------------------------------------------------------
# README gallery block generation
# --------------------------------------------------------------------------

def stem_to_title(stem: str) -> str:
    return stem.replace("_", " ").replace("-", " ").strip().title()


def collect_pieces(gallery_dir: Path, skip_dirs=("hero", "failures")):
    pieces = []
    for d in sorted(gallery_dir.iterdir()):
        if not d.is_dir() or d.name in skip_dirs:
            continue
        images = sorted(d.glob("*.jpg")) + sorted(d.glob("*.jpeg"))
        if not images:
            continue
        image = images[0]
        index_sheet = d / "_index.png"
        caption_file = d / "caption.txt"
        caption = None
        if caption_file.exists():
            lines = caption_file.read_text().strip().splitlines()
            caption = lines[0] if lines else None
        pieces.append({
            "name": d.name,
            "title": stem_to_title(d.name),
            "image": image,
            "index_sheet": index_sheet if index_sheet.exists() else None,
            "caption": caption,
        })
    return pieces


def build_piece_section(piece: dict, gallery_dir: Path) -> str:
    def rel(p: Path) -> str:
        try:
            return p.resolve().relative_to(gallery_dir.resolve()).as_posix()
        except ValueError:
            return p.as_posix()

    lines = [f"### {piece['title']}", ""]
    if piece["caption"]:
        lines.append(f"*{piece['caption']}*")
        lines.append("")

    lines.append("<table>")
    lines.append("  <tr>")
    lines.append('    <td width="50%" align="center">')
    lines.append(f'      <img src="{rel(piece["image"])}" alt="{piece["title"]} -- finished piece" width="100%">')
    lines.append("      <br><sub>Finished piece</sub>")
    lines.append("    </td>")
    if piece["index_sheet"] is not None:
        lines.append('    <td width="50%" align="center">')
        lines.append(f'      <img src="{rel(piece["index_sheet"])}" alt="{piece["title"]} -- index sheet" width="100%">')
        lines.append("      <br><sub>Index sheet -- every anodized layer that went into this piece</sub>")
        lines.append("    </td>")
    else:
        lines.append('    <td width="50%" align="center"><sub><i>(no index sheet on file for this piece)</i></sub></td>')
    lines.append("  </tr>")
    lines.append("</table>")
    return "\n".join(lines)


def build_gallery_block(pieces, gallery_dir: Path) -> str:
    lines = [GALLERY_START, ""]
    if not pieces:
        lines.append("_Gallery is empty -- add a piece with `../scripts/manage_gallery.py`._")
    else:
        sections = [build_piece_section(p, gallery_dir) for p in pieces]
        lines.append("\n\n---\n\n".join(sections))
    lines.append("")
    lines.append(GALLERY_END)
    return "\n".join(lines)


DEFAULT_INTRO = (
    "# Gallery\n\n"
    "Every piece below is shown with its finished photo next to the index "
    "sheet from that run -- the actual map of anodized layers that produced "
    "it. Nothing here is printed or filtered onto the metal: each color is "
    "its own anodize / laser-ablate / re-anodize cycle on titanium.\n"
)


def regenerate_readme(gallery_dir: Path, readme_path: Path) -> None:
    pieces = collect_pieces(gallery_dir)
    block = build_gallery_block(pieces, gallery_dir=gallery_dir)

    if not readme_path.exists():
        new_text = DEFAULT_INTRO + "\n" + block + "\n"
        note = "Created"
    else:
        text = readme_path.read_text()
        if GALLERY_START in text and GALLERY_END in text:
            pre = text.split(GALLERY_START)[0]
            post = text.split(GALLERY_END)[1]
            new_text = pre + block + post
            note = "Updated existing gallery block in"
        else:
            new_text = text.rstrip("\n") + "\n\n" + block + "\n"
            note = "No gallery markers found -- appended a new gallery block to"

    readme_path.write_text(new_text)
    print(f"{note} {readme_path} ({len(pieces)} piece(s)).")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image", type=Path, help="finished photo to add/replace in the gallery")
    ap.add_argument("--quality", type=int, default=95, help="JPEG quality if conversion is needed (default 95)")
    ap.add_argument("--readme", type=Path, default=Path("README.md"),
                     help="path to the gallery README.md to update (default: ./README.md, i.e. gallery/README.md)")
    args = ap.parse_args()

    gallery_dir = Path(".").resolve()

    index_src = gallery_dir / "_index.png"
    if not index_src.exists():
        raise SystemExit(
            f"Expected an _index.png in {gallery_dir} (the separator's index sheet "
            f"for this piece) but didn't find one.\n"
            f"Drop the run's _index.png here before running this script."
        )

    if not args.image.exists():
        raise SystemExit(f"Image not found: {args.image}")
    if args.image.suffix.lower() not in IMAGE_EXTS:
        raise SystemExit(f"Unrecognized image type: {args.image.suffix}")

    piece_name = args.image.stem
    piece_dir = gallery_dir / piece_name
    is_replace = piece_dir.exists()
    piece_dir.mkdir(exist_ok=True)

    # Clear stale image files from a previous version of this piece (e.g.
    # extension changed between runs) -- but never touch caption.txt.
    for old in piece_dir.iterdir():
        if old.suffix.lower() in IMAGE_EXTS:
            old.unlink()

    dst_image = piece_dir / f"{piece_name}.jpg"
    convert_to_jpg(args.image, dst_image, quality=args.quality)

    dst_index = piece_dir / "_index.png"
    shutil.move(str(index_src), str(dst_index))

    print(f"{'Replaced' if is_replace else 'Added'} '{piece_name}' -> {piece_dir}/")

    regenerate_readme(gallery_dir, args.readme)


if __name__ == "__main__":
    main()
